# Generated by Django 2.2.6 on 2019-12-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0004_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='leasing',
            field=models.ManyToManyField(blank=True, null=True, to='p_library.Friend'),
        ),
    ]
