# Generated by Django 2.2.6 on 2019-12-17 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0005_book_leasing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='leasing',
        ),
        migrations.CreateModel(
            name='Leasing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p_library.Book')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p_library.Friend')),
                ('leasing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leasinged_books', to='p_library.Friend')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='leasing_friends',
            field=models.ManyToManyField(through='p_library.Leasing', to='p_library.Friend'),
        ),
    ]
