# Generated by Django 2.2.6 on 2019-12-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0006_auto_20191217_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='leasing_friends',
        ),
        migrations.AddField(
            model_name='book',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='books', to='p_library.Friend'),
        ),
        migrations.DeleteModel(
            name='Leasing',
        ),
    ]
