# Generated by Django 2.2.6 on 2019-12-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0007_auto_20191218_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='leasing_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
