# Generated by Django 2.2.6 on 2019-12-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0008_book_leasing_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='book_avatars/%Y/%m/%d'),
        ),
    ]
