# Generated by Django 2.2.6 on 2019-12-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0009_book_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='avatar',
            field=models.ImageField(blank=True, height_field='50', upload_to='book_avatars/%Y/%m/%d', width_field='50'),
        ),
    ]
